services:
  einote-db:
    image: postgres:16-alpine
    container_name: einote-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: einote
      TZ: 'Asia/Jakarta'
    volumes:
      - ./composedata/postgresql:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "7432:5432"  