# docker build -f Dockerfile.core  -t einote:core-0.1.0 .

# Stage 1: Build the Go application
FROM golang:1.23 AS builder

WORKDIR /app
COPY core/go.mod core/go.sum ./
RUN go mod download
COPY core/ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o einote cmd/app/main.go

# Stage 2: Run the Go application
FROM alpine:latest

COPY --from=builder /app/einote /einote
RUN touch .env

EXPOSE 8080

CMD ["/einote"]
